# Default values for wildfly
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  tag: latest
build:
  enabled: true
  mode: bootable-jar
  bootableJar:
    builderImage: registry.access.redhat.com/ubi8/openjdk-11:latest
  s2i:
    version: latest
    jdk: "11"
    arch: amd64
    amd64:
      jdk11:
        builderImage: registry.redhat.io/jboss-eap-7/eap-xp3-openjdk11-openshift-rhel8
        runtimeImage: registry.redhat.io/jboss-eap-7/eap-xp3-openjdk11-runtime-openshift-rhel8
  output:
    kind: "ImageStreamTag"
  triggers: {}
deploy:
  enabled: true
  replicas: 1
  route:
    enabled: true
    tls:
      enabled: true
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
  livenessProbe:
    httpGet:
      path: /health/live
      port: admin
    initialDelaySeconds: 60
  readinessProbe:
    httpGet:
      path: /health/ready
      port: admin
    initialDelaySeconds: 60

